apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-nginx.fullname" . }}
data:
  index.html: |
    <h1>Hello World</h1>
    {{- range $name, $config := .Values.additionaltext }}
    <h1>{{ $config.header }}</h1><p>{{ $config.text }}</p>
    {{- end }}
